host: localhost
port: 8052
base_path: "/api/user"
mysql:
  host: "localhost"
  user: "root"
  password: "Far@1234"
  db: "signin"
  dialect: "mysql"
  pool:
    max: 5
    min: 0
    acquire: 30000
    idle: 10000
smtp:
  service: "gmail"
  username: "faraj@binmile.com"
  password: "Far@12589308"
referral:
  base_path: "http://127.0.0.1:8001/api/referral/usercode"
  method: "POST"
wallet:
  base_path: "http://127.0.0.1:8005/api/wallet/user"
  method: "POST"
